name: app_bhb
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # === Librairies principales ===
  flutter_svg: ^2.0.7
  fpdart: ^1.1.1
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  dartz: ^0.10.1
  get_it: ^8.2.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  image_picker: ^1.1.1
  flutter_localization: ^0.3.3
  url_launcher: ^6.3.0
  flutter_animate: ^4.5.0
  pdf: ^3.10.7
  printing: ^5.13.3
  path_provider: ^2.1.5
  firebase_storage: ^13.0.4
  open_filex: ^4.7.0
  collection: ^1.17.0
  image: ^4.1.2
  qr: ^3.0.2
  file_picker: ^10.3.6
  font_awesome_flutter: ^10.12.0
  cloud_functions: ^6.0.4
  fl_chart: ^1.1.1
  share_plus: ^12.0.1
  signature: ^6.3.0
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/app_logo.png"

flutter:
  uses-material-design: true

  # === Images et ressources ===
  assets:
    - assets/img/
    - assets/font/

  # === Déclaration de la police personnalisée ===
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/font/Tajawal-Regular.ttf
        - asset: assets/font/NotoSansArabic-Regular.ttf
        - asset: assets/font/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/font/Tajawal-ExtraBold.ttf
          weight: 800
